import {
  CREATE_PRODUCT_MAX_VARIANTS,
  DEFAULT_PRODUCT_CURRENCY,
  PRODUCT_NAME_MAX,
} from "@showzy/validation/catalog";

export { PRODUCT_NAME_MAX };

export const PRODUCT_FORM_MAX_VARIANTS = CREATE_PRODUCT_MAX_VARIANTS;
export const PRODUCT_CURRENCY = DEFAULT_PRODUCT_CURRENCY;
