import { showzyEslintConfig } from "@showzy/tooling/eslint";

import { webLayerBoundariesRule } from "./eslint/web-layer-boundaries.mjs";

const webPlugin = {
  meta: { name: "showzy-web", version: "0.0.0" },
  rules: {
    "layer-boundaries": webLayerBoundariesRule,
  },
};

export default [
  // Generated by @tanstack/router-plugin on dev/build; not hand-written code.
  { ignores: ["src/routeTree.gen.ts"] },
  ...showzyEslintConfig({ tsconfigRootDir: import.meta.dirname }),
  {
    plugins: { "showzy-web": webPlugin },
    rules: {
      "showzy-web/layer-boundaries": "error",
    },
  },
  {
    files: ["src/routes/**/*.{ts,tsx}"],
    rules: {
      // `throw redirect()` is the TanStack Router navigation API; the
      // value is not an `Error` subclass.
      "@typescript-eslint/only-throw-error": [
        "error",
        {
          allow: [
            {
              from: "package",
              package: "@tanstack/react-router",
              name: ["Redirect"],
            },
            {
              from: "package",
              package: "@tanstack/router-core",
              name: ["Redirect"],
            },
          ],
        },
      ],
    },
  },
];
