import { showzyEslintConfig } from "@showzy/tooling/eslint";

export default [
  // Generated by @tanstack/router-plugin on dev/build; not hand-written code.
  { ignores: ["src/routeTree.gen.ts"] },
  ...showzyEslintConfig({ tsconfigRootDir: import.meta.dirname }),
  {
    files: ["src/routes/**/*.{ts,tsx}"],
    rules: {
      // `throw redirect()` is the TanStack Router navigation API; the
      // value is not an `Error` subclass.
      "@typescript-eslint/only-throw-error": [
        "error",
        {
          allow: [
            {
              from: "package",
              package: "@tanstack/react-router",
              name: ["Redirect"],
            },
            {
              from: "package",
              package: "@tanstack/router-core",
              name: ["Redirect"],
            },
          ],
        },
      ],
    },
  },
];
