import { showzyEslintConfig } from "@showzy/tooling/eslint";

export default [
  // Generated by @tanstack/router-plugin on dev/build; not hand-written code.
  { ignores: ["src/routeTree.gen.ts"] },
  ...showzyEslintConfig({ tsconfigRootDir: import.meta.dirname }),
];
