import type { SuiteCoverageManifest } from "@showzy/core";

export const customersSuiteCoverage = {
  isolation: [
    "customers.archiveCustomer",
    "customers.createCustomer",
    "customers.createGroup",
    "customers.deleteCustomer",
    "customers.deleteGroup",
    "customers.getCustomer",
    "customers.getCustomerPricingFacts",
    "customers.getGroup",
    "customers.listCustomers",
    "customers.listGroups",
    "customers.restoreCustomer",
    "customers.updateCustomer",
    "customers.updateGroup",
  ],
  publicProjection: [],
  consumerIsolation: [],
  accountIsolation: [],
  shareIsolation: [],
  idempotency: [
    "customers.archiveCustomer",
    "customers.createCustomer",
    "customers.createGroup",
    "customers.deleteCustomer",
    "customers.deleteGroup",
    "customers.restoreCustomer",
    "customers.updateCustomer",
    "customers.updateGroup",
  ],
  events: [],
  atomic: [],
} as const satisfies SuiteCoverageManifest;
