/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedCompanySlugRouteRouteImport } from './routes/_authed/$companySlug/route'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedCompanySlugFullRouteRouteImport } from './routes/_authed/$companySlug/_full/route'
import { Route as AuthedCompanySlugPanelRouteRouteImport } from './routes/_authed/$companySlug/_panel/route'
import { Route as AuthedCompanySlugPanelIndexRouteImport } from './routes/_authed/$companySlug/_panel/index'
import { Route as AuthedCompanySlugPanelCompanyRouteRouteImport } from './routes/_authed/$companySlug/_panel/company/route'
import { Route as AuthedCompanySlugPanelCustomersRouteRouteImport } from './routes/_authed/$companySlug/_panel/customers/route'
import { Route as AuthedCompanySlugPanelDocumentsRouteRouteImport } from './routes/_authed/$companySlug/_panel/documents/route'
import { Route as AuthedCompanySlugPanelInvitesRouteRouteImport } from './routes/_authed/$companySlug/_panel/invites/route'
import { Route as AuthedCompanySlugPanelOrdersRouteRouteImport } from './routes/_authed/$companySlug/_panel/orders/route'
import { Route as AuthedCompanySlugPanelPricingRouteRouteImport } from './routes/_authed/$companySlug/_panel/pricing/route'
import { Route as AuthedCompanySlugPanelProductsRouteRouteImport } from './routes/_authed/$companySlug/_panel/products/route'
import { Route as AuthedCompanySlugPanelCompanyIndexRouteImport } from './routes/_authed/$companySlug/_panel/company/index'
import { Route as AuthedCompanySlugPanelCompanyLegalRouteImport } from './routes/_authed/$companySlug/_panel/company/legal'
import { Route as AuthedCompanySlugPanelCompanyTeamRouteImport } from './routes/_authed/$companySlug/_panel/company/team'
import { Route as AuthedCompanySlugPanelCustomersIndexRouteImport } from './routes/_authed/$companySlug/_panel/customers/index'
import { Route as AuthedCompanySlugPanelCustomersCustomerIdRouteImport } from './routes/_authed/$companySlug/_panel/customers/$customerId'
import { Route as AuthedCompanySlugPanelCustomersCounterpartiesRouteRouteImport } from './routes/_authed/$companySlug/_panel/customers/counterparties/route'
import { Route as AuthedCompanySlugPanelCustomersGroupsRouteRouteImport } from './routes/_authed/$companySlug/_panel/customers/groups/route'
import { Route as AuthedCompanySlugPanelCustomersNewRouteImport } from './routes/_authed/$companySlug/_panel/customers/new'
import { Route as AuthedCompanySlugPanelDocumentsIndexRouteImport } from './routes/_authed/$companySlug/_panel/documents/index'
import { Route as AuthedCompanySlugPanelDocumentsDocumentIdRouteImport } from './routes/_authed/$companySlug/_panel/documents/$documentId'
import { Route as AuthedCompanySlugPanelDocumentsNewRouteImport } from './routes/_authed/$companySlug/_panel/documents/new'
import { Route as AuthedCompanySlugPanelDocumentsTemplatesRouteRouteImport } from './routes/_authed/$companySlug/_panel/documents/templates/route'
import { Route as AuthedCompanySlugPanelInvitesIndexRouteImport } from './routes/_authed/$companySlug/_panel/invites/index'
import { Route as AuthedCompanySlugPanelInvitesInviteIdRouteImport } from './routes/_authed/$companySlug/_panel/invites/$inviteId'
import { Route as AuthedCompanySlugPanelInvitesNewRouteImport } from './routes/_authed/$companySlug/_panel/invites/new'
import { Route as AuthedCompanySlugPanelOrdersIndexRouteImport } from './routes/_authed/$companySlug/_panel/orders/index'
import { Route as AuthedCompanySlugPanelOrdersOrderIdRouteImport } from './routes/_authed/$companySlug/_panel/orders/$orderId'
import { Route as AuthedCompanySlugPanelOrdersNewRouteImport } from './routes/_authed/$companySlug/_panel/orders/new'
import { Route as AuthedCompanySlugPanelPricingIndexRouteImport } from './routes/_authed/$companySlug/_panel/pricing/index'
import { Route as AuthedCompanySlugPanelPricingPriceListIdRouteRouteImport } from './routes/_authed/$companySlug/_panel/pricing/$priceListId/route'
import { Route as AuthedCompanySlugPanelPricingNewRouteImport } from './routes/_authed/$companySlug/_panel/pricing/new'
import { Route as AuthedCompanySlugPanelProductsIndexRouteImport } from './routes/_authed/$companySlug/_panel/products/index'
import { Route as AuthedCompanySlugPanelProductsProductIdRouteRouteImport } from './routes/_authed/$companySlug/_panel/products/$productId/route'
import { Route as AuthedCompanySlugPanelProductsNewRouteImport } from './routes/_authed/$companySlug/_panel/products/new'
import { Route as AuthedCompanySlugPanelCustomersCounterpartiesIndexRouteImport } from './routes/_authed/$companySlug/_panel/customers/counterparties/index'
import { Route as AuthedCompanySlugPanelCustomersCounterpartiesCounterpartyIdRouteImport } from './routes/_authed/$companySlug/_panel/customers/counterparties/$counterpartyId'
import { Route as AuthedCompanySlugPanelCustomersCounterpartiesNewRouteImport } from './routes/_authed/$companySlug/_panel/customers/counterparties/new'
import { Route as AuthedCompanySlugPanelCustomersGroupsIndexRouteImport } from './routes/_authed/$companySlug/_panel/customers/groups/index'
import { Route as AuthedCompanySlugPanelCustomersGroupsGroupIdRouteImport } from './routes/_authed/$companySlug/_panel/customers/groups/$groupId'
import { Route as AuthedCompanySlugPanelCustomersGroupsNewRouteImport } from './routes/_authed/$companySlug/_panel/customers/groups/new'
import { Route as AuthedCompanySlugPanelDocumentsTemplatesIndexRouteImport } from './routes/_authed/$companySlug/_panel/documents/templates/index'
import { Route as AuthedCompanySlugPanelDocumentsTemplatesTemplateIdRouteImport } from './routes/_authed/$companySlug/_panel/documents/templates/$templateId'
import { Route as AuthedCompanySlugPanelPricingPriceListIdIndexRouteImport } from './routes/_authed/$companySlug/_panel/pricing/$priceListId/index'
import { Route as AuthedCompanySlugPanelPricingPriceListIdEditRouteImport } from './routes/_authed/$companySlug/_panel/pricing/$priceListId/edit'
import { Route as AuthedCompanySlugPanelProductsProductIdIndexRouteImport } from './routes/_authed/$companySlug/_panel/products/$productId/index'
import { Route as AuthedCompanySlugPanelProductsProductIdEditRouteImport } from './routes/_authed/$companySlug/_panel/products/$productId/edit'
import { Route as AuthedCompanySlugFullDocumentsTemplatesTemplateIdEditRouteImport } from './routes/_authed/$companySlug/_full/documents/templates/$templateId/edit'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompanySlugRouteRoute = AuthedCompanySlugRouteRouteImport.update({
  id: '/$companySlug',
  path: '/$companySlug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompanySlugFullRouteRoute =
  AuthedCompanySlugFullRouteRouteImport.update({
    id: '/_full',
    getParentRoute: () => AuthedCompanySlugRouteRoute,
  } as any)
const AuthedCompanySlugPanelRouteRoute =
  AuthedCompanySlugPanelRouteRouteImport.update({
    id: '/_panel',
    getParentRoute: () => AuthedCompanySlugRouteRoute,
  } as any)
const AuthedCompanySlugPanelIndexRoute =
  AuthedCompanySlugPanelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCompanySlugPanelRouteRoute,
  } as any)
const AuthedCompanySlugPanelCompanyRouteRoute =
  AuthedCompanySlugPanelCompanyRouteRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthedCompanySlugPanelRouteRoute,
  } as any)
const AuthedCompanySlugPanelCustomersRouteRoute =
  AuthedCompanySlugPanelCustomersRouteRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthedCompanySlugPanelRouteRoute,
  } as any)
const AuthedCompanySlugPanelDocumentsRouteRoute =
  AuthedCompanySlugPanelDocumentsRouteRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthedCompanySlugPanelRouteRoute,
  } as any)
const AuthedCompanySlugPanelInvitesRouteRoute =
  AuthedCompanySlugPanelInvitesRouteRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthedCompanySlugPanelRouteRoute,
  } as any)
const AuthedCompanySlugPanelOrdersRouteRoute =
  AuthedCompanySlugPanelOrdersRouteRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthedCompanySlugPanelRouteRoute,
  } as any)
const AuthedCompanySlugPanelPricingRouteRoute =
  AuthedCompanySlugPanelPricingRouteRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthedCompanySlugPanelRouteRoute,
  } as any)
const AuthedCompanySlugPanelProductsRouteRoute =
  AuthedCompanySlugPanelProductsRouteRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthedCompanySlugPanelRouteRoute,
  } as any)
const AuthedCompanySlugPanelCompanyIndexRoute =
  AuthedCompanySlugPanelCompanyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCompanySlugPanelCompanyRouteRoute,
  } as any)
const AuthedCompanySlugPanelCompanyLegalRoute =
  AuthedCompanySlugPanelCompanyLegalRouteImport.update({
    id: '/legal',
    path: '/legal',
    getParentRoute: () => AuthedCompanySlugPanelCompanyRouteRoute,
  } as any)
const AuthedCompanySlugPanelCompanyTeamRoute =
  AuthedCompanySlugPanelCompanyTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthedCompanySlugPanelCompanyRouteRoute,
  } as any)
const AuthedCompanySlugPanelCustomersIndexRoute =
  AuthedCompanySlugPanelCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCompanySlugPanelCustomersRouteRoute,
  } as any)
const AuthedCompanySlugPanelCustomersCustomerIdRoute =
  AuthedCompanySlugPanelCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthedCompanySlugPanelCustomersRouteRoute,
  } as any)
const AuthedCompanySlugPanelCustomersCounterpartiesRouteRoute =
  AuthedCompanySlugPanelCustomersCounterpartiesRouteRouteImport.update({
    id: '/counterparties',
    path: '/counterparties',
    getParentRoute: () => AuthedCompanySlugPanelCustomersRouteRoute,
  } as any)
const AuthedCompanySlugPanelCustomersGroupsRouteRoute =
  AuthedCompanySlugPanelCustomersGroupsRouteRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthedCompanySlugPanelCustomersRouteRoute,
  } as any)
const AuthedCompanySlugPanelCustomersNewRoute =
  AuthedCompanySlugPanelCustomersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthedCompanySlugPanelCustomersRouteRoute,
  } as any)
const AuthedCompanySlugPanelDocumentsIndexRoute =
  AuthedCompanySlugPanelDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCompanySlugPanelDocumentsRouteRoute,
  } as any)
const AuthedCompanySlugPanelDocumentsDocumentIdRoute =
  AuthedCompanySlugPanelDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AuthedCompanySlugPanelDocumentsRouteRoute,
  } as any)
const AuthedCompanySlugPanelDocumentsNewRoute =
  AuthedCompanySlugPanelDocumentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthedCompanySlugPanelDocumentsRouteRoute,
  } as any)
const AuthedCompanySlugPanelDocumentsTemplatesRouteRoute =
  AuthedCompanySlugPanelDocumentsTemplatesRouteRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthedCompanySlugPanelDocumentsRouteRoute,
  } as any)
const AuthedCompanySlugPanelInvitesIndexRoute =
  AuthedCompanySlugPanelInvitesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCompanySlugPanelInvitesRouteRoute,
  } as any)
const AuthedCompanySlugPanelInvitesInviteIdRoute =
  AuthedCompanySlugPanelInvitesInviteIdRouteImport.update({
    id: '/$inviteId',
    path: '/$inviteId',
    getParentRoute: () => AuthedCompanySlugPanelInvitesRouteRoute,
  } as any)
const AuthedCompanySlugPanelInvitesNewRoute =
  AuthedCompanySlugPanelInvitesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthedCompanySlugPanelInvitesRouteRoute,
  } as any)
const AuthedCompanySlugPanelOrdersIndexRoute =
  AuthedCompanySlugPanelOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCompanySlugPanelOrdersRouteRoute,
  } as any)
const AuthedCompanySlugPanelOrdersOrderIdRoute =
  AuthedCompanySlugPanelOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthedCompanySlugPanelOrdersRouteRoute,
  } as any)
const AuthedCompanySlugPanelOrdersNewRoute =
  AuthedCompanySlugPanelOrdersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthedCompanySlugPanelOrdersRouteRoute,
  } as any)
const AuthedCompanySlugPanelPricingIndexRoute =
  AuthedCompanySlugPanelPricingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCompanySlugPanelPricingRouteRoute,
  } as any)
const AuthedCompanySlugPanelPricingPriceListIdRouteRoute =
  AuthedCompanySlugPanelPricingPriceListIdRouteRouteImport.update({
    id: '/$priceListId',
    path: '/$priceListId',
    getParentRoute: () => AuthedCompanySlugPanelPricingRouteRoute,
  } as any)
const AuthedCompanySlugPanelPricingNewRoute =
  AuthedCompanySlugPanelPricingNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthedCompanySlugPanelPricingRouteRoute,
  } as any)
const AuthedCompanySlugPanelProductsIndexRoute =
  AuthedCompanySlugPanelProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCompanySlugPanelProductsRouteRoute,
  } as any)
const AuthedCompanySlugPanelProductsProductIdRouteRoute =
  AuthedCompanySlugPanelProductsProductIdRouteRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthedCompanySlugPanelProductsRouteRoute,
  } as any)
const AuthedCompanySlugPanelProductsNewRoute =
  AuthedCompanySlugPanelProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthedCompanySlugPanelProductsRouteRoute,
  } as any)
const AuthedCompanySlugPanelCustomersCounterpartiesIndexRoute =
  AuthedCompanySlugPanelCustomersCounterpartiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthedCompanySlugPanelCustomersCounterpartiesRouteRoute,
  } as any)
const AuthedCompanySlugPanelCustomersCounterpartiesCounterpartyIdRoute =
  AuthedCompanySlugPanelCustomersCounterpartiesCounterpartyIdRouteImport.update(
    {
      id: '/$counterpartyId',
      path: '/$counterpartyId',
      getParentRoute: () =>
        AuthedCompanySlugPanelCustomersCounterpartiesRouteRoute,
    } as any,
  )
const AuthedCompanySlugPanelCustomersCounterpartiesNewRoute =
  AuthedCompanySlugPanelCustomersCounterpartiesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () =>
      AuthedCompanySlugPanelCustomersCounterpartiesRouteRoute,
  } as any)
const AuthedCompanySlugPanelCustomersGroupsIndexRoute =
  AuthedCompanySlugPanelCustomersGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCompanySlugPanelCustomersGroupsRouteRoute,
  } as any)
const AuthedCompanySlugPanelCustomersGroupsGroupIdRoute =
  AuthedCompanySlugPanelCustomersGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthedCompanySlugPanelCustomersGroupsRouteRoute,
  } as any)
const AuthedCompanySlugPanelCustomersGroupsNewRoute =
  AuthedCompanySlugPanelCustomersGroupsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthedCompanySlugPanelCustomersGroupsRouteRoute,
  } as any)
const AuthedCompanySlugPanelDocumentsTemplatesIndexRoute =
  AuthedCompanySlugPanelDocumentsTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCompanySlugPanelDocumentsTemplatesRouteRoute,
  } as any)
const AuthedCompanySlugPanelDocumentsTemplatesTemplateIdRoute =
  AuthedCompanySlugPanelDocumentsTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => AuthedCompanySlugPanelDocumentsTemplatesRouteRoute,
  } as any)
const AuthedCompanySlugPanelPricingPriceListIdIndexRoute =
  AuthedCompanySlugPanelPricingPriceListIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCompanySlugPanelPricingPriceListIdRouteRoute,
  } as any)
const AuthedCompanySlugPanelPricingPriceListIdEditRoute =
  AuthedCompanySlugPanelPricingPriceListIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedCompanySlugPanelPricingPriceListIdRouteRoute,
  } as any)
const AuthedCompanySlugPanelProductsProductIdIndexRoute =
  AuthedCompanySlugPanelProductsProductIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCompanySlugPanelProductsProductIdRouteRoute,
  } as any)
const AuthedCompanySlugPanelProductsProductIdEditRoute =
  AuthedCompanySlugPanelProductsProductIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedCompanySlugPanelProductsProductIdRouteRoute,
  } as any)
const AuthedCompanySlugFullDocumentsTemplatesTemplateIdEditRoute =
  AuthedCompanySlugFullDocumentsTemplatesTemplateIdEditRouteImport.update({
    id: '/documents/templates/$templateId/edit',
    path: '/documents/templates/$templateId/edit',
    getParentRoute: () => AuthedCompanySlugFullRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/$companySlug': typeof AuthedCompanySlugRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/verify': typeof AuthVerifyRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/$companySlug/company': typeof AuthedCompanySlugPanelCompanyRouteRouteWithChildren
  '/$companySlug/customers': typeof AuthedCompanySlugPanelCustomersRouteRouteWithChildren
  '/$companySlug/documents': typeof AuthedCompanySlugPanelDocumentsRouteRouteWithChildren
  '/$companySlug/invites': typeof AuthedCompanySlugPanelInvitesRouteRouteWithChildren
  '/$companySlug/orders': typeof AuthedCompanySlugPanelOrdersRouteRouteWithChildren
  '/$companySlug/pricing': typeof AuthedCompanySlugPanelPricingRouteRouteWithChildren
  '/$companySlug/products': typeof AuthedCompanySlugPanelProductsRouteRouteWithChildren
  '/$companySlug/': typeof AuthedCompanySlugPanelIndexRoute
  '/$companySlug/customers/counterparties': typeof AuthedCompanySlugPanelCustomersCounterpartiesRouteRouteWithChildren
  '/$companySlug/customers/groups': typeof AuthedCompanySlugPanelCustomersGroupsRouteRouteWithChildren
  '/$companySlug/documents/templates': typeof AuthedCompanySlugPanelDocumentsTemplatesRouteRouteWithChildren
  '/$companySlug/pricing/$priceListId': typeof AuthedCompanySlugPanelPricingPriceListIdRouteRouteWithChildren
  '/$companySlug/products/$productId': typeof AuthedCompanySlugPanelProductsProductIdRouteRouteWithChildren
  '/$companySlug/company/legal': typeof AuthedCompanySlugPanelCompanyLegalRoute
  '/$companySlug/company/team': typeof AuthedCompanySlugPanelCompanyTeamRoute
  '/$companySlug/customers/$customerId': typeof AuthedCompanySlugPanelCustomersCustomerIdRoute
  '/$companySlug/customers/new': typeof AuthedCompanySlugPanelCustomersNewRoute
  '/$companySlug/documents/$documentId': typeof AuthedCompanySlugPanelDocumentsDocumentIdRoute
  '/$companySlug/documents/new': typeof AuthedCompanySlugPanelDocumentsNewRoute
  '/$companySlug/invites/$inviteId': typeof AuthedCompanySlugPanelInvitesInviteIdRoute
  '/$companySlug/invites/new': typeof AuthedCompanySlugPanelInvitesNewRoute
  '/$companySlug/orders/$orderId': typeof AuthedCompanySlugPanelOrdersOrderIdRoute
  '/$companySlug/orders/new': typeof AuthedCompanySlugPanelOrdersNewRoute
  '/$companySlug/pricing/new': typeof AuthedCompanySlugPanelPricingNewRoute
  '/$companySlug/products/new': typeof AuthedCompanySlugPanelProductsNewRoute
  '/$companySlug/company/': typeof AuthedCompanySlugPanelCompanyIndexRoute
  '/$companySlug/customers/': typeof AuthedCompanySlugPanelCustomersIndexRoute
  '/$companySlug/documents/': typeof AuthedCompanySlugPanelDocumentsIndexRoute
  '/$companySlug/invites/': typeof AuthedCompanySlugPanelInvitesIndexRoute
  '/$companySlug/orders/': typeof AuthedCompanySlugPanelOrdersIndexRoute
  '/$companySlug/pricing/': typeof AuthedCompanySlugPanelPricingIndexRoute
  '/$companySlug/products/': typeof AuthedCompanySlugPanelProductsIndexRoute
  '/$companySlug/customers/counterparties/$counterpartyId': typeof AuthedCompanySlugPanelCustomersCounterpartiesCounterpartyIdRoute
  '/$companySlug/customers/counterparties/new': typeof AuthedCompanySlugPanelCustomersCounterpartiesNewRoute
  '/$companySlug/customers/groups/$groupId': typeof AuthedCompanySlugPanelCustomersGroupsGroupIdRoute
  '/$companySlug/customers/groups/new': typeof AuthedCompanySlugPanelCustomersGroupsNewRoute
  '/$companySlug/documents/templates/$templateId': typeof AuthedCompanySlugPanelDocumentsTemplatesTemplateIdRoute
  '/$companySlug/pricing/$priceListId/edit': typeof AuthedCompanySlugPanelPricingPriceListIdEditRoute
  '/$companySlug/products/$productId/edit': typeof AuthedCompanySlugPanelProductsProductIdEditRoute
  '/$companySlug/customers/counterparties/': typeof AuthedCompanySlugPanelCustomersCounterpartiesIndexRoute
  '/$companySlug/customers/groups/': typeof AuthedCompanySlugPanelCustomersGroupsIndexRoute
  '/$companySlug/documents/templates/': typeof AuthedCompanySlugPanelDocumentsTemplatesIndexRoute
  '/$companySlug/pricing/$priceListId/': typeof AuthedCompanySlugPanelPricingPriceListIdIndexRoute
  '/$companySlug/products/$productId/': typeof AuthedCompanySlugPanelProductsProductIdIndexRoute
  '/$companySlug/documents/templates/$templateId/edit': typeof AuthedCompanySlugFullDocumentsTemplatesTemplateIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/$companySlug': typeof AuthedCompanySlugPanelIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/verify': typeof AuthVerifyRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/$companySlug/company/legal': typeof AuthedCompanySlugPanelCompanyLegalRoute
  '/$companySlug/company/team': typeof AuthedCompanySlugPanelCompanyTeamRoute
  '/$companySlug/customers/$customerId': typeof AuthedCompanySlugPanelCustomersCustomerIdRoute
  '/$companySlug/customers/new': typeof AuthedCompanySlugPanelCustomersNewRoute
  '/$companySlug/documents/$documentId': typeof AuthedCompanySlugPanelDocumentsDocumentIdRoute
  '/$companySlug/documents/new': typeof AuthedCompanySlugPanelDocumentsNewRoute
  '/$companySlug/invites/$inviteId': typeof AuthedCompanySlugPanelInvitesInviteIdRoute
  '/$companySlug/invites/new': typeof AuthedCompanySlugPanelInvitesNewRoute
  '/$companySlug/orders/$orderId': typeof AuthedCompanySlugPanelOrdersOrderIdRoute
  '/$companySlug/orders/new': typeof AuthedCompanySlugPanelOrdersNewRoute
  '/$companySlug/pricing/new': typeof AuthedCompanySlugPanelPricingNewRoute
  '/$companySlug/products/new': typeof AuthedCompanySlugPanelProductsNewRoute
  '/$companySlug/company': typeof AuthedCompanySlugPanelCompanyIndexRoute
  '/$companySlug/customers': typeof AuthedCompanySlugPanelCustomersIndexRoute
  '/$companySlug/documents': typeof AuthedCompanySlugPanelDocumentsIndexRoute
  '/$companySlug/invites': typeof AuthedCompanySlugPanelInvitesIndexRoute
  '/$companySlug/orders': typeof AuthedCompanySlugPanelOrdersIndexRoute
  '/$companySlug/pricing': typeof AuthedCompanySlugPanelPricingIndexRoute
  '/$companySlug/products': typeof AuthedCompanySlugPanelProductsIndexRoute
  '/$companySlug/customers/counterparties/$counterpartyId': typeof AuthedCompanySlugPanelCustomersCounterpartiesCounterpartyIdRoute
  '/$companySlug/customers/counterparties/new': typeof AuthedCompanySlugPanelCustomersCounterpartiesNewRoute
  '/$companySlug/customers/groups/$groupId': typeof AuthedCompanySlugPanelCustomersGroupsGroupIdRoute
  '/$companySlug/customers/groups/new': typeof AuthedCompanySlugPanelCustomersGroupsNewRoute
  '/$companySlug/documents/templates/$templateId': typeof AuthedCompanySlugPanelDocumentsTemplatesTemplateIdRoute
  '/$companySlug/pricing/$priceListId/edit': typeof AuthedCompanySlugPanelPricingPriceListIdEditRoute
  '/$companySlug/products/$productId/edit': typeof AuthedCompanySlugPanelProductsProductIdEditRoute
  '/$companySlug/customers/counterparties': typeof AuthedCompanySlugPanelCustomersCounterpartiesIndexRoute
  '/$companySlug/customers/groups': typeof AuthedCompanySlugPanelCustomersGroupsIndexRoute
  '/$companySlug/documents/templates': typeof AuthedCompanySlugPanelDocumentsTemplatesIndexRoute
  '/$companySlug/pricing/$priceListId': typeof AuthedCompanySlugPanelPricingPriceListIdIndexRoute
  '/$companySlug/products/$productId': typeof AuthedCompanySlugPanelProductsProductIdIndexRoute
  '/$companySlug/documents/templates/$templateId/edit': typeof AuthedCompanySlugFullDocumentsTemplatesTemplateIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/$companySlug': typeof AuthedCompanySlugRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/$companySlug/_full': typeof AuthedCompanySlugFullRouteRouteWithChildren
  '/_authed/$companySlug/_panel': typeof AuthedCompanySlugPanelRouteRouteWithChildren
  '/_authed/$companySlug/_panel/company': typeof AuthedCompanySlugPanelCompanyRouteRouteWithChildren
  '/_authed/$companySlug/_panel/customers': typeof AuthedCompanySlugPanelCustomersRouteRouteWithChildren
  '/_authed/$companySlug/_panel/documents': typeof AuthedCompanySlugPanelDocumentsRouteRouteWithChildren
  '/_authed/$companySlug/_panel/invites': typeof AuthedCompanySlugPanelInvitesRouteRouteWithChildren
  '/_authed/$companySlug/_panel/orders': typeof AuthedCompanySlugPanelOrdersRouteRouteWithChildren
  '/_authed/$companySlug/_panel/pricing': typeof AuthedCompanySlugPanelPricingRouteRouteWithChildren
  '/_authed/$companySlug/_panel/products': typeof AuthedCompanySlugPanelProductsRouteRouteWithChildren
  '/_authed/$companySlug/_panel/': typeof AuthedCompanySlugPanelIndexRoute
  '/_authed/$companySlug/_panel/customers/counterparties': typeof AuthedCompanySlugPanelCustomersCounterpartiesRouteRouteWithChildren
  '/_authed/$companySlug/_panel/customers/groups': typeof AuthedCompanySlugPanelCustomersGroupsRouteRouteWithChildren
  '/_authed/$companySlug/_panel/documents/templates': typeof AuthedCompanySlugPanelDocumentsTemplatesRouteRouteWithChildren
  '/_authed/$companySlug/_panel/pricing/$priceListId': typeof AuthedCompanySlugPanelPricingPriceListIdRouteRouteWithChildren
  '/_authed/$companySlug/_panel/products/$productId': typeof AuthedCompanySlugPanelProductsProductIdRouteRouteWithChildren
  '/_authed/$companySlug/_panel/company/legal': typeof AuthedCompanySlugPanelCompanyLegalRoute
  '/_authed/$companySlug/_panel/company/team': typeof AuthedCompanySlugPanelCompanyTeamRoute
  '/_authed/$companySlug/_panel/customers/$customerId': typeof AuthedCompanySlugPanelCustomersCustomerIdRoute
  '/_authed/$companySlug/_panel/customers/new': typeof AuthedCompanySlugPanelCustomersNewRoute
  '/_authed/$companySlug/_panel/documents/$documentId': typeof AuthedCompanySlugPanelDocumentsDocumentIdRoute
  '/_authed/$companySlug/_panel/documents/new': typeof AuthedCompanySlugPanelDocumentsNewRoute
  '/_authed/$companySlug/_panel/invites/$inviteId': typeof AuthedCompanySlugPanelInvitesInviteIdRoute
  '/_authed/$companySlug/_panel/invites/new': typeof AuthedCompanySlugPanelInvitesNewRoute
  '/_authed/$companySlug/_panel/orders/$orderId': typeof AuthedCompanySlugPanelOrdersOrderIdRoute
  '/_authed/$companySlug/_panel/orders/new': typeof AuthedCompanySlugPanelOrdersNewRoute
  '/_authed/$companySlug/_panel/pricing/new': typeof AuthedCompanySlugPanelPricingNewRoute
  '/_authed/$companySlug/_panel/products/new': typeof AuthedCompanySlugPanelProductsNewRoute
  '/_authed/$companySlug/_panel/company/': typeof AuthedCompanySlugPanelCompanyIndexRoute
  '/_authed/$companySlug/_panel/customers/': typeof AuthedCompanySlugPanelCustomersIndexRoute
  '/_authed/$companySlug/_panel/documents/': typeof AuthedCompanySlugPanelDocumentsIndexRoute
  '/_authed/$companySlug/_panel/invites/': typeof AuthedCompanySlugPanelInvitesIndexRoute
  '/_authed/$companySlug/_panel/orders/': typeof AuthedCompanySlugPanelOrdersIndexRoute
  '/_authed/$companySlug/_panel/pricing/': typeof AuthedCompanySlugPanelPricingIndexRoute
  '/_authed/$companySlug/_panel/products/': typeof AuthedCompanySlugPanelProductsIndexRoute
  '/_authed/$companySlug/_panel/customers/counterparties/$counterpartyId': typeof AuthedCompanySlugPanelCustomersCounterpartiesCounterpartyIdRoute
  '/_authed/$companySlug/_panel/customers/counterparties/new': typeof AuthedCompanySlugPanelCustomersCounterpartiesNewRoute
  '/_authed/$companySlug/_panel/customers/groups/$groupId': typeof AuthedCompanySlugPanelCustomersGroupsGroupIdRoute
  '/_authed/$companySlug/_panel/customers/groups/new': typeof AuthedCompanySlugPanelCustomersGroupsNewRoute
  '/_authed/$companySlug/_panel/documents/templates/$templateId': typeof AuthedCompanySlugPanelDocumentsTemplatesTemplateIdRoute
  '/_authed/$companySlug/_panel/pricing/$priceListId/edit': typeof AuthedCompanySlugPanelPricingPriceListIdEditRoute
  '/_authed/$companySlug/_panel/products/$productId/edit': typeof AuthedCompanySlugPanelProductsProductIdEditRoute
  '/_authed/$companySlug/_panel/customers/counterparties/': typeof AuthedCompanySlugPanelCustomersCounterpartiesIndexRoute
  '/_authed/$companySlug/_panel/customers/groups/': typeof AuthedCompanySlugPanelCustomersGroupsIndexRoute
  '/_authed/$companySlug/_panel/documents/templates/': typeof AuthedCompanySlugPanelDocumentsTemplatesIndexRoute
  '/_authed/$companySlug/_panel/pricing/$priceListId/': typeof AuthedCompanySlugPanelPricingPriceListIdIndexRoute
  '/_authed/$companySlug/_panel/products/$productId/': typeof AuthedCompanySlugPanelProductsProductIdIndexRoute
  '/_authed/$companySlug/_full/documents/templates/$templateId/edit': typeof AuthedCompanySlugFullDocumentsTemplatesTemplateIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$companySlug'
    | '/sign-in'
    | '/verify'
    | '/onboarding'
    | '/$companySlug/company'
    | '/$companySlug/customers'
    | '/$companySlug/documents'
    | '/$companySlug/invites'
    | '/$companySlug/orders'
    | '/$companySlug/pricing'
    | '/$companySlug/products'
    | '/$companySlug/'
    | '/$companySlug/customers/counterparties'
    | '/$companySlug/customers/groups'
    | '/$companySlug/documents/templates'
    | '/$companySlug/pricing/$priceListId'
    | '/$companySlug/products/$productId'
    | '/$companySlug/company/legal'
    | '/$companySlug/company/team'
    | '/$companySlug/customers/$customerId'
    | '/$companySlug/customers/new'
    | '/$companySlug/documents/$documentId'
    | '/$companySlug/documents/new'
    | '/$companySlug/invites/$inviteId'
    | '/$companySlug/invites/new'
    | '/$companySlug/orders/$orderId'
    | '/$companySlug/orders/new'
    | '/$companySlug/pricing/new'
    | '/$companySlug/products/new'
    | '/$companySlug/company/'
    | '/$companySlug/customers/'
    | '/$companySlug/documents/'
    | '/$companySlug/invites/'
    | '/$companySlug/orders/'
    | '/$companySlug/pricing/'
    | '/$companySlug/products/'
    | '/$companySlug/customers/counterparties/$counterpartyId'
    | '/$companySlug/customers/counterparties/new'
    | '/$companySlug/customers/groups/$groupId'
    | '/$companySlug/customers/groups/new'
    | '/$companySlug/documents/templates/$templateId'
    | '/$companySlug/pricing/$priceListId/edit'
    | '/$companySlug/products/$productId/edit'
    | '/$companySlug/customers/counterparties/'
    | '/$companySlug/customers/groups/'
    | '/$companySlug/documents/templates/'
    | '/$companySlug/pricing/$priceListId/'
    | '/$companySlug/products/$productId/'
    | '/$companySlug/documents/templates/$templateId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$companySlug'
    | '/sign-in'
    | '/verify'
    | '/onboarding'
    | '/$companySlug/company/legal'
    | '/$companySlug/company/team'
    | '/$companySlug/customers/$customerId'
    | '/$companySlug/customers/new'
    | '/$companySlug/documents/$documentId'
    | '/$companySlug/documents/new'
    | '/$companySlug/invites/$inviteId'
    | '/$companySlug/invites/new'
    | '/$companySlug/orders/$orderId'
    | '/$companySlug/orders/new'
    | '/$companySlug/pricing/new'
    | '/$companySlug/products/new'
    | '/$companySlug/company'
    | '/$companySlug/customers'
    | '/$companySlug/documents'
    | '/$companySlug/invites'
    | '/$companySlug/orders'
    | '/$companySlug/pricing'
    | '/$companySlug/products'
    | '/$companySlug/customers/counterparties/$counterpartyId'
    | '/$companySlug/customers/counterparties/new'
    | '/$companySlug/customers/groups/$groupId'
    | '/$companySlug/customers/groups/new'
    | '/$companySlug/documents/templates/$templateId'
    | '/$companySlug/pricing/$priceListId/edit'
    | '/$companySlug/products/$productId/edit'
    | '/$companySlug/customers/counterparties'
    | '/$companySlug/customers/groups'
    | '/$companySlug/documents/templates'
    | '/$companySlug/pricing/$priceListId'
    | '/$companySlug/products/$productId'
    | '/$companySlug/documents/templates/$templateId/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_authed'
    | '/_authed/$companySlug'
    | '/_auth/sign-in'
    | '/_auth/verify'
    | '/_authed/onboarding'
    | '/_authed/'
    | '/_authed/$companySlug/_full'
    | '/_authed/$companySlug/_panel'
    | '/_authed/$companySlug/_panel/company'
    | '/_authed/$companySlug/_panel/customers'
    | '/_authed/$companySlug/_panel/documents'
    | '/_authed/$companySlug/_panel/invites'
    | '/_authed/$companySlug/_panel/orders'
    | '/_authed/$companySlug/_panel/pricing'
    | '/_authed/$companySlug/_panel/products'
    | '/_authed/$companySlug/_panel/'
    | '/_authed/$companySlug/_panel/customers/counterparties'
    | '/_authed/$companySlug/_panel/customers/groups'
    | '/_authed/$companySlug/_panel/documents/templates'
    | '/_authed/$companySlug/_panel/pricing/$priceListId'
    | '/_authed/$companySlug/_panel/products/$productId'
    | '/_authed/$companySlug/_panel/company/legal'
    | '/_authed/$companySlug/_panel/company/team'
    | '/_authed/$companySlug/_panel/customers/$customerId'
    | '/_authed/$companySlug/_panel/customers/new'
    | '/_authed/$companySlug/_panel/documents/$documentId'
    | '/_authed/$companySlug/_panel/documents/new'
    | '/_authed/$companySlug/_panel/invites/$inviteId'
    | '/_authed/$companySlug/_panel/invites/new'
    | '/_authed/$companySlug/_panel/orders/$orderId'
    | '/_authed/$companySlug/_panel/orders/new'
    | '/_authed/$companySlug/_panel/pricing/new'
    | '/_authed/$companySlug/_panel/products/new'
    | '/_authed/$companySlug/_panel/company/'
    | '/_authed/$companySlug/_panel/customers/'
    | '/_authed/$companySlug/_panel/documents/'
    | '/_authed/$companySlug/_panel/invites/'
    | '/_authed/$companySlug/_panel/orders/'
    | '/_authed/$companySlug/_panel/pricing/'
    | '/_authed/$companySlug/_panel/products/'
    | '/_authed/$companySlug/_panel/customers/counterparties/$counterpartyId'
    | '/_authed/$companySlug/_panel/customers/counterparties/new'
    | '/_authed/$companySlug/_panel/customers/groups/$groupId'
    | '/_authed/$companySlug/_panel/customers/groups/new'
    | '/_authed/$companySlug/_panel/documents/templates/$templateId'
    | '/_authed/$companySlug/_panel/pricing/$priceListId/edit'
    | '/_authed/$companySlug/_panel/products/$productId/edit'
    | '/_authed/$companySlug/_panel/customers/counterparties/'
    | '/_authed/$companySlug/_panel/customers/groups/'
    | '/_authed/$companySlug/_panel/documents/templates/'
    | '/_authed/$companySlug/_panel/pricing/$priceListId/'
    | '/_authed/$companySlug/_panel/products/$productId/'
    | '/_authed/$companySlug/_full/documents/templates/$templateId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$companySlug': {
      id: '/_authed/$companySlug'
      path: '/$companySlug'
      fullPath: '/$companySlug'
      preLoaderRoute: typeof AuthedCompanySlugRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$companySlug/_full': {
      id: '/_authed/$companySlug/_full'
      path: ''
      fullPath: '/$companySlug'
      preLoaderRoute: typeof AuthedCompanySlugFullRouteRouteImport
      parentRoute: typeof AuthedCompanySlugRouteRoute
    }
    '/_authed/$companySlug/_panel': {
      id: '/_authed/$companySlug/_panel'
      path: ''
      fullPath: '/$companySlug'
      preLoaderRoute: typeof AuthedCompanySlugPanelRouteRouteImport
      parentRoute: typeof AuthedCompanySlugRouteRoute
    }
    '/_authed/$companySlug/_panel/': {
      id: '/_authed/$companySlug/_panel/'
      path: '/'
      fullPath: '/$companySlug/'
      preLoaderRoute: typeof AuthedCompanySlugPanelIndexRouteImport
      parentRoute: typeof AuthedCompanySlugPanelRouteRoute
    }
    '/_authed/$companySlug/_panel/company': {
      id: '/_authed/$companySlug/_panel/company'
      path: '/company'
      fullPath: '/$companySlug/company'
      preLoaderRoute: typeof AuthedCompanySlugPanelCompanyRouteRouteImport
      parentRoute: typeof AuthedCompanySlugPanelRouteRoute
    }
    '/_authed/$companySlug/_panel/customers': {
      id: '/_authed/$companySlug/_panel/customers'
      path: '/customers'
      fullPath: '/$companySlug/customers'
      preLoaderRoute: typeof AuthedCompanySlugPanelCustomersRouteRouteImport
      parentRoute: typeof AuthedCompanySlugPanelRouteRoute
    }
    '/_authed/$companySlug/_panel/documents': {
      id: '/_authed/$companySlug/_panel/documents'
      path: '/documents'
      fullPath: '/$companySlug/documents'
      preLoaderRoute: typeof AuthedCompanySlugPanelDocumentsRouteRouteImport
      parentRoute: typeof AuthedCompanySlugPanelRouteRoute
    }
    '/_authed/$companySlug/_panel/invites': {
      id: '/_authed/$companySlug/_panel/invites'
      path: '/invites'
      fullPath: '/$companySlug/invites'
      preLoaderRoute: typeof AuthedCompanySlugPanelInvitesRouteRouteImport
      parentRoute: typeof AuthedCompanySlugPanelRouteRoute
    }
    '/_authed/$companySlug/_panel/orders': {
      id: '/_authed/$companySlug/_panel/orders'
      path: '/orders'
      fullPath: '/$companySlug/orders'
      preLoaderRoute: typeof AuthedCompanySlugPanelOrdersRouteRouteImport
      parentRoute: typeof AuthedCompanySlugPanelRouteRoute
    }
    '/_authed/$companySlug/_panel/pricing': {
      id: '/_authed/$companySlug/_panel/pricing'
      path: '/pricing'
      fullPath: '/$companySlug/pricing'
      preLoaderRoute: typeof AuthedCompanySlugPanelPricingRouteRouteImport
      parentRoute: typeof AuthedCompanySlugPanelRouteRoute
    }
    '/_authed/$companySlug/_panel/products': {
      id: '/_authed/$companySlug/_panel/products'
      path: '/products'
      fullPath: '/$companySlug/products'
      preLoaderRoute: typeof AuthedCompanySlugPanelProductsRouteRouteImport
      parentRoute: typeof AuthedCompanySlugPanelRouteRoute
    }
    '/_authed/$companySlug/_panel/company/': {
      id: '/_authed/$companySlug/_panel/company/'
      path: '/'
      fullPath: '/$companySlug/company/'
      preLoaderRoute: typeof AuthedCompanySlugPanelCompanyIndexRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCompanyRouteRoute
    }
    '/_authed/$companySlug/_panel/company/legal': {
      id: '/_authed/$companySlug/_panel/company/legal'
      path: '/legal'
      fullPath: '/$companySlug/company/legal'
      preLoaderRoute: typeof AuthedCompanySlugPanelCompanyLegalRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCompanyRouteRoute
    }
    '/_authed/$companySlug/_panel/company/team': {
      id: '/_authed/$companySlug/_panel/company/team'
      path: '/team'
      fullPath: '/$companySlug/company/team'
      preLoaderRoute: typeof AuthedCompanySlugPanelCompanyTeamRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCompanyRouteRoute
    }
    '/_authed/$companySlug/_panel/customers/': {
      id: '/_authed/$companySlug/_panel/customers/'
      path: '/'
      fullPath: '/$companySlug/customers/'
      preLoaderRoute: typeof AuthedCompanySlugPanelCustomersIndexRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCustomersRouteRoute
    }
    '/_authed/$companySlug/_panel/customers/$customerId': {
      id: '/_authed/$companySlug/_panel/customers/$customerId'
      path: '/$customerId'
      fullPath: '/$companySlug/customers/$customerId'
      preLoaderRoute: typeof AuthedCompanySlugPanelCustomersCustomerIdRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCustomersRouteRoute
    }
    '/_authed/$companySlug/_panel/customers/counterparties': {
      id: '/_authed/$companySlug/_panel/customers/counterparties'
      path: '/counterparties'
      fullPath: '/$companySlug/customers/counterparties'
      preLoaderRoute: typeof AuthedCompanySlugPanelCustomersCounterpartiesRouteRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCustomersRouteRoute
    }
    '/_authed/$companySlug/_panel/customers/groups': {
      id: '/_authed/$companySlug/_panel/customers/groups'
      path: '/groups'
      fullPath: '/$companySlug/customers/groups'
      preLoaderRoute: typeof AuthedCompanySlugPanelCustomersGroupsRouteRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCustomersRouteRoute
    }
    '/_authed/$companySlug/_panel/customers/new': {
      id: '/_authed/$companySlug/_panel/customers/new'
      path: '/new'
      fullPath: '/$companySlug/customers/new'
      preLoaderRoute: typeof AuthedCompanySlugPanelCustomersNewRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCustomersRouteRoute
    }
    '/_authed/$companySlug/_panel/documents/': {
      id: '/_authed/$companySlug/_panel/documents/'
      path: '/'
      fullPath: '/$companySlug/documents/'
      preLoaderRoute: typeof AuthedCompanySlugPanelDocumentsIndexRouteImport
      parentRoute: typeof AuthedCompanySlugPanelDocumentsRouteRoute
    }
    '/_authed/$companySlug/_panel/documents/$documentId': {
      id: '/_authed/$companySlug/_panel/documents/$documentId'
      path: '/$documentId'
      fullPath: '/$companySlug/documents/$documentId'
      preLoaderRoute: typeof AuthedCompanySlugPanelDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthedCompanySlugPanelDocumentsRouteRoute
    }
    '/_authed/$companySlug/_panel/documents/new': {
      id: '/_authed/$companySlug/_panel/documents/new'
      path: '/new'
      fullPath: '/$companySlug/documents/new'
      preLoaderRoute: typeof AuthedCompanySlugPanelDocumentsNewRouteImport
      parentRoute: typeof AuthedCompanySlugPanelDocumentsRouteRoute
    }
    '/_authed/$companySlug/_panel/documents/templates': {
      id: '/_authed/$companySlug/_panel/documents/templates'
      path: '/templates'
      fullPath: '/$companySlug/documents/templates'
      preLoaderRoute: typeof AuthedCompanySlugPanelDocumentsTemplatesRouteRouteImport
      parentRoute: typeof AuthedCompanySlugPanelDocumentsRouteRoute
    }
    '/_authed/$companySlug/_panel/invites/': {
      id: '/_authed/$companySlug/_panel/invites/'
      path: '/'
      fullPath: '/$companySlug/invites/'
      preLoaderRoute: typeof AuthedCompanySlugPanelInvitesIndexRouteImport
      parentRoute: typeof AuthedCompanySlugPanelInvitesRouteRoute
    }
    '/_authed/$companySlug/_panel/invites/$inviteId': {
      id: '/_authed/$companySlug/_panel/invites/$inviteId'
      path: '/$inviteId'
      fullPath: '/$companySlug/invites/$inviteId'
      preLoaderRoute: typeof AuthedCompanySlugPanelInvitesInviteIdRouteImport
      parentRoute: typeof AuthedCompanySlugPanelInvitesRouteRoute
    }
    '/_authed/$companySlug/_panel/invites/new': {
      id: '/_authed/$companySlug/_panel/invites/new'
      path: '/new'
      fullPath: '/$companySlug/invites/new'
      preLoaderRoute: typeof AuthedCompanySlugPanelInvitesNewRouteImport
      parentRoute: typeof AuthedCompanySlugPanelInvitesRouteRoute
    }
    '/_authed/$companySlug/_panel/orders/': {
      id: '/_authed/$companySlug/_panel/orders/'
      path: '/'
      fullPath: '/$companySlug/orders/'
      preLoaderRoute: typeof AuthedCompanySlugPanelOrdersIndexRouteImport
      parentRoute: typeof AuthedCompanySlugPanelOrdersRouteRoute
    }
    '/_authed/$companySlug/_panel/orders/$orderId': {
      id: '/_authed/$companySlug/_panel/orders/$orderId'
      path: '/$orderId'
      fullPath: '/$companySlug/orders/$orderId'
      preLoaderRoute: typeof AuthedCompanySlugPanelOrdersOrderIdRouteImport
      parentRoute: typeof AuthedCompanySlugPanelOrdersRouteRoute
    }
    '/_authed/$companySlug/_panel/orders/new': {
      id: '/_authed/$companySlug/_panel/orders/new'
      path: '/new'
      fullPath: '/$companySlug/orders/new'
      preLoaderRoute: typeof AuthedCompanySlugPanelOrdersNewRouteImport
      parentRoute: typeof AuthedCompanySlugPanelOrdersRouteRoute
    }
    '/_authed/$companySlug/_panel/pricing/': {
      id: '/_authed/$companySlug/_panel/pricing/'
      path: '/'
      fullPath: '/$companySlug/pricing/'
      preLoaderRoute: typeof AuthedCompanySlugPanelPricingIndexRouteImport
      parentRoute: typeof AuthedCompanySlugPanelPricingRouteRoute
    }
    '/_authed/$companySlug/_panel/pricing/$priceListId': {
      id: '/_authed/$companySlug/_panel/pricing/$priceListId'
      path: '/$priceListId'
      fullPath: '/$companySlug/pricing/$priceListId'
      preLoaderRoute: typeof AuthedCompanySlugPanelPricingPriceListIdRouteRouteImport
      parentRoute: typeof AuthedCompanySlugPanelPricingRouteRoute
    }
    '/_authed/$companySlug/_panel/pricing/new': {
      id: '/_authed/$companySlug/_panel/pricing/new'
      path: '/new'
      fullPath: '/$companySlug/pricing/new'
      preLoaderRoute: typeof AuthedCompanySlugPanelPricingNewRouteImport
      parentRoute: typeof AuthedCompanySlugPanelPricingRouteRoute
    }
    '/_authed/$companySlug/_panel/products/': {
      id: '/_authed/$companySlug/_panel/products/'
      path: '/'
      fullPath: '/$companySlug/products/'
      preLoaderRoute: typeof AuthedCompanySlugPanelProductsIndexRouteImport
      parentRoute: typeof AuthedCompanySlugPanelProductsRouteRoute
    }
    '/_authed/$companySlug/_panel/products/$productId': {
      id: '/_authed/$companySlug/_panel/products/$productId'
      path: '/$productId'
      fullPath: '/$companySlug/products/$productId'
      preLoaderRoute: typeof AuthedCompanySlugPanelProductsProductIdRouteRouteImport
      parentRoute: typeof AuthedCompanySlugPanelProductsRouteRoute
    }
    '/_authed/$companySlug/_panel/products/new': {
      id: '/_authed/$companySlug/_panel/products/new'
      path: '/new'
      fullPath: '/$companySlug/products/new'
      preLoaderRoute: typeof AuthedCompanySlugPanelProductsNewRouteImport
      parentRoute: typeof AuthedCompanySlugPanelProductsRouteRoute
    }
    '/_authed/$companySlug/_panel/customers/counterparties/': {
      id: '/_authed/$companySlug/_panel/customers/counterparties/'
      path: '/'
      fullPath: '/$companySlug/customers/counterparties/'
      preLoaderRoute: typeof AuthedCompanySlugPanelCustomersCounterpartiesIndexRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCustomersCounterpartiesRouteRoute
    }
    '/_authed/$companySlug/_panel/customers/counterparties/$counterpartyId': {
      id: '/_authed/$companySlug/_panel/customers/counterparties/$counterpartyId'
      path: '/$counterpartyId'
      fullPath: '/$companySlug/customers/counterparties/$counterpartyId'
      preLoaderRoute: typeof AuthedCompanySlugPanelCustomersCounterpartiesCounterpartyIdRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCustomersCounterpartiesRouteRoute
    }
    '/_authed/$companySlug/_panel/customers/counterparties/new': {
      id: '/_authed/$companySlug/_panel/customers/counterparties/new'
      path: '/new'
      fullPath: '/$companySlug/customers/counterparties/new'
      preLoaderRoute: typeof AuthedCompanySlugPanelCustomersCounterpartiesNewRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCustomersCounterpartiesRouteRoute
    }
    '/_authed/$companySlug/_panel/customers/groups/': {
      id: '/_authed/$companySlug/_panel/customers/groups/'
      path: '/'
      fullPath: '/$companySlug/customers/groups/'
      preLoaderRoute: typeof AuthedCompanySlugPanelCustomersGroupsIndexRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCustomersGroupsRouteRoute
    }
    '/_authed/$companySlug/_panel/customers/groups/$groupId': {
      id: '/_authed/$companySlug/_panel/customers/groups/$groupId'
      path: '/$groupId'
      fullPath: '/$companySlug/customers/groups/$groupId'
      preLoaderRoute: typeof AuthedCompanySlugPanelCustomersGroupsGroupIdRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCustomersGroupsRouteRoute
    }
    '/_authed/$companySlug/_panel/customers/groups/new': {
      id: '/_authed/$companySlug/_panel/customers/groups/new'
      path: '/new'
      fullPath: '/$companySlug/customers/groups/new'
      preLoaderRoute: typeof AuthedCompanySlugPanelCustomersGroupsNewRouteImport
      parentRoute: typeof AuthedCompanySlugPanelCustomersGroupsRouteRoute
    }
    '/_authed/$companySlug/_panel/documents/templates/': {
      id: '/_authed/$companySlug/_panel/documents/templates/'
      path: '/'
      fullPath: '/$companySlug/documents/templates/'
      preLoaderRoute: typeof AuthedCompanySlugPanelDocumentsTemplatesIndexRouteImport
      parentRoute: typeof AuthedCompanySlugPanelDocumentsTemplatesRouteRoute
    }
    '/_authed/$companySlug/_panel/documents/templates/$templateId': {
      id: '/_authed/$companySlug/_panel/documents/templates/$templateId'
      path: '/$templateId'
      fullPath: '/$companySlug/documents/templates/$templateId'
      preLoaderRoute: typeof AuthedCompanySlugPanelDocumentsTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthedCompanySlugPanelDocumentsTemplatesRouteRoute
    }
    '/_authed/$companySlug/_panel/pricing/$priceListId/': {
      id: '/_authed/$companySlug/_panel/pricing/$priceListId/'
      path: '/'
      fullPath: '/$companySlug/pricing/$priceListId/'
      preLoaderRoute: typeof AuthedCompanySlugPanelPricingPriceListIdIndexRouteImport
      parentRoute: typeof AuthedCompanySlugPanelPricingPriceListIdRouteRoute
    }
    '/_authed/$companySlug/_panel/pricing/$priceListId/edit': {
      id: '/_authed/$companySlug/_panel/pricing/$priceListId/edit'
      path: '/edit'
      fullPath: '/$companySlug/pricing/$priceListId/edit'
      preLoaderRoute: typeof AuthedCompanySlugPanelPricingPriceListIdEditRouteImport
      parentRoute: typeof AuthedCompanySlugPanelPricingPriceListIdRouteRoute
    }
    '/_authed/$companySlug/_panel/products/$productId/': {
      id: '/_authed/$companySlug/_panel/products/$productId/'
      path: '/'
      fullPath: '/$companySlug/products/$productId/'
      preLoaderRoute: typeof AuthedCompanySlugPanelProductsProductIdIndexRouteImport
      parentRoute: typeof AuthedCompanySlugPanelProductsProductIdRouteRoute
    }
    '/_authed/$companySlug/_panel/products/$productId/edit': {
      id: '/_authed/$companySlug/_panel/products/$productId/edit'
      path: '/edit'
      fullPath: '/$companySlug/products/$productId/edit'
      preLoaderRoute: typeof AuthedCompanySlugPanelProductsProductIdEditRouteImport
      parentRoute: typeof AuthedCompanySlugPanelProductsProductIdRouteRoute
    }
    '/_authed/$companySlug/_full/documents/templates/$templateId/edit': {
      id: '/_authed/$companySlug/_full/documents/templates/$templateId/edit'
      path: '/documents/templates/$templateId/edit'
      fullPath: '/$companySlug/documents/templates/$templateId/edit'
      preLoaderRoute: typeof AuthedCompanySlugFullDocumentsTemplatesTemplateIdEditRouteImport
      parentRoute: typeof AuthedCompanySlugFullRouteRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthedCompanySlugFullRouteRouteChildren {
  AuthedCompanySlugFullDocumentsTemplatesTemplateIdEditRoute: typeof AuthedCompanySlugFullDocumentsTemplatesTemplateIdEditRoute
}

const AuthedCompanySlugFullRouteRouteChildren: AuthedCompanySlugFullRouteRouteChildren =
  {
    AuthedCompanySlugFullDocumentsTemplatesTemplateIdEditRoute:
      AuthedCompanySlugFullDocumentsTemplatesTemplateIdEditRoute,
  }

const AuthedCompanySlugFullRouteRouteWithChildren =
  AuthedCompanySlugFullRouteRoute._addFileChildren(
    AuthedCompanySlugFullRouteRouteChildren,
  )

interface AuthedCompanySlugPanelCompanyRouteRouteChildren {
  AuthedCompanySlugPanelCompanyLegalRoute: typeof AuthedCompanySlugPanelCompanyLegalRoute
  AuthedCompanySlugPanelCompanyTeamRoute: typeof AuthedCompanySlugPanelCompanyTeamRoute
  AuthedCompanySlugPanelCompanyIndexRoute: typeof AuthedCompanySlugPanelCompanyIndexRoute
}

const AuthedCompanySlugPanelCompanyRouteRouteChildren: AuthedCompanySlugPanelCompanyRouteRouteChildren =
  {
    AuthedCompanySlugPanelCompanyLegalRoute:
      AuthedCompanySlugPanelCompanyLegalRoute,
    AuthedCompanySlugPanelCompanyTeamRoute:
      AuthedCompanySlugPanelCompanyTeamRoute,
    AuthedCompanySlugPanelCompanyIndexRoute:
      AuthedCompanySlugPanelCompanyIndexRoute,
  }

const AuthedCompanySlugPanelCompanyRouteRouteWithChildren =
  AuthedCompanySlugPanelCompanyRouteRoute._addFileChildren(
    AuthedCompanySlugPanelCompanyRouteRouteChildren,
  )

interface AuthedCompanySlugPanelCustomersCounterpartiesRouteRouteChildren {
  AuthedCompanySlugPanelCustomersCounterpartiesCounterpartyIdRoute: typeof AuthedCompanySlugPanelCustomersCounterpartiesCounterpartyIdRoute
  AuthedCompanySlugPanelCustomersCounterpartiesNewRoute: typeof AuthedCompanySlugPanelCustomersCounterpartiesNewRoute
  AuthedCompanySlugPanelCustomersCounterpartiesIndexRoute: typeof AuthedCompanySlugPanelCustomersCounterpartiesIndexRoute
}

const AuthedCompanySlugPanelCustomersCounterpartiesRouteRouteChildren: AuthedCompanySlugPanelCustomersCounterpartiesRouteRouteChildren =
  {
    AuthedCompanySlugPanelCustomersCounterpartiesCounterpartyIdRoute:
      AuthedCompanySlugPanelCustomersCounterpartiesCounterpartyIdRoute,
    AuthedCompanySlugPanelCustomersCounterpartiesNewRoute:
      AuthedCompanySlugPanelCustomersCounterpartiesNewRoute,
    AuthedCompanySlugPanelCustomersCounterpartiesIndexRoute:
      AuthedCompanySlugPanelCustomersCounterpartiesIndexRoute,
  }

const AuthedCompanySlugPanelCustomersCounterpartiesRouteRouteWithChildren =
  AuthedCompanySlugPanelCustomersCounterpartiesRouteRoute._addFileChildren(
    AuthedCompanySlugPanelCustomersCounterpartiesRouteRouteChildren,
  )

interface AuthedCompanySlugPanelCustomersGroupsRouteRouteChildren {
  AuthedCompanySlugPanelCustomersGroupsGroupIdRoute: typeof AuthedCompanySlugPanelCustomersGroupsGroupIdRoute
  AuthedCompanySlugPanelCustomersGroupsNewRoute: typeof AuthedCompanySlugPanelCustomersGroupsNewRoute
  AuthedCompanySlugPanelCustomersGroupsIndexRoute: typeof AuthedCompanySlugPanelCustomersGroupsIndexRoute
}

const AuthedCompanySlugPanelCustomersGroupsRouteRouteChildren: AuthedCompanySlugPanelCustomersGroupsRouteRouteChildren =
  {
    AuthedCompanySlugPanelCustomersGroupsGroupIdRoute:
      AuthedCompanySlugPanelCustomersGroupsGroupIdRoute,
    AuthedCompanySlugPanelCustomersGroupsNewRoute:
      AuthedCompanySlugPanelCustomersGroupsNewRoute,
    AuthedCompanySlugPanelCustomersGroupsIndexRoute:
      AuthedCompanySlugPanelCustomersGroupsIndexRoute,
  }

const AuthedCompanySlugPanelCustomersGroupsRouteRouteWithChildren =
  AuthedCompanySlugPanelCustomersGroupsRouteRoute._addFileChildren(
    AuthedCompanySlugPanelCustomersGroupsRouteRouteChildren,
  )

interface AuthedCompanySlugPanelCustomersRouteRouteChildren {
  AuthedCompanySlugPanelCustomersCounterpartiesRouteRoute: typeof AuthedCompanySlugPanelCustomersCounterpartiesRouteRouteWithChildren
  AuthedCompanySlugPanelCustomersGroupsRouteRoute: typeof AuthedCompanySlugPanelCustomersGroupsRouteRouteWithChildren
  AuthedCompanySlugPanelCustomersCustomerIdRoute: typeof AuthedCompanySlugPanelCustomersCustomerIdRoute
  AuthedCompanySlugPanelCustomersNewRoute: typeof AuthedCompanySlugPanelCustomersNewRoute
  AuthedCompanySlugPanelCustomersIndexRoute: typeof AuthedCompanySlugPanelCustomersIndexRoute
}

const AuthedCompanySlugPanelCustomersRouteRouteChildren: AuthedCompanySlugPanelCustomersRouteRouteChildren =
  {
    AuthedCompanySlugPanelCustomersCounterpartiesRouteRoute:
      AuthedCompanySlugPanelCustomersCounterpartiesRouteRouteWithChildren,
    AuthedCompanySlugPanelCustomersGroupsRouteRoute:
      AuthedCompanySlugPanelCustomersGroupsRouteRouteWithChildren,
    AuthedCompanySlugPanelCustomersCustomerIdRoute:
      AuthedCompanySlugPanelCustomersCustomerIdRoute,
    AuthedCompanySlugPanelCustomersNewRoute:
      AuthedCompanySlugPanelCustomersNewRoute,
    AuthedCompanySlugPanelCustomersIndexRoute:
      AuthedCompanySlugPanelCustomersIndexRoute,
  }

const AuthedCompanySlugPanelCustomersRouteRouteWithChildren =
  AuthedCompanySlugPanelCustomersRouteRoute._addFileChildren(
    AuthedCompanySlugPanelCustomersRouteRouteChildren,
  )

interface AuthedCompanySlugPanelDocumentsTemplatesRouteRouteChildren {
  AuthedCompanySlugPanelDocumentsTemplatesTemplateIdRoute: typeof AuthedCompanySlugPanelDocumentsTemplatesTemplateIdRoute
  AuthedCompanySlugPanelDocumentsTemplatesIndexRoute: typeof AuthedCompanySlugPanelDocumentsTemplatesIndexRoute
}

const AuthedCompanySlugPanelDocumentsTemplatesRouteRouteChildren: AuthedCompanySlugPanelDocumentsTemplatesRouteRouteChildren =
  {
    AuthedCompanySlugPanelDocumentsTemplatesTemplateIdRoute:
      AuthedCompanySlugPanelDocumentsTemplatesTemplateIdRoute,
    AuthedCompanySlugPanelDocumentsTemplatesIndexRoute:
      AuthedCompanySlugPanelDocumentsTemplatesIndexRoute,
  }

const AuthedCompanySlugPanelDocumentsTemplatesRouteRouteWithChildren =
  AuthedCompanySlugPanelDocumentsTemplatesRouteRoute._addFileChildren(
    AuthedCompanySlugPanelDocumentsTemplatesRouteRouteChildren,
  )

interface AuthedCompanySlugPanelDocumentsRouteRouteChildren {
  AuthedCompanySlugPanelDocumentsTemplatesRouteRoute: typeof AuthedCompanySlugPanelDocumentsTemplatesRouteRouteWithChildren
  AuthedCompanySlugPanelDocumentsDocumentIdRoute: typeof AuthedCompanySlugPanelDocumentsDocumentIdRoute
  AuthedCompanySlugPanelDocumentsNewRoute: typeof AuthedCompanySlugPanelDocumentsNewRoute
  AuthedCompanySlugPanelDocumentsIndexRoute: typeof AuthedCompanySlugPanelDocumentsIndexRoute
}

const AuthedCompanySlugPanelDocumentsRouteRouteChildren: AuthedCompanySlugPanelDocumentsRouteRouteChildren =
  {
    AuthedCompanySlugPanelDocumentsTemplatesRouteRoute:
      AuthedCompanySlugPanelDocumentsTemplatesRouteRouteWithChildren,
    AuthedCompanySlugPanelDocumentsDocumentIdRoute:
      AuthedCompanySlugPanelDocumentsDocumentIdRoute,
    AuthedCompanySlugPanelDocumentsNewRoute:
      AuthedCompanySlugPanelDocumentsNewRoute,
    AuthedCompanySlugPanelDocumentsIndexRoute:
      AuthedCompanySlugPanelDocumentsIndexRoute,
  }

const AuthedCompanySlugPanelDocumentsRouteRouteWithChildren =
  AuthedCompanySlugPanelDocumentsRouteRoute._addFileChildren(
    AuthedCompanySlugPanelDocumentsRouteRouteChildren,
  )

interface AuthedCompanySlugPanelInvitesRouteRouteChildren {
  AuthedCompanySlugPanelInvitesInviteIdRoute: typeof AuthedCompanySlugPanelInvitesInviteIdRoute
  AuthedCompanySlugPanelInvitesNewRoute: typeof AuthedCompanySlugPanelInvitesNewRoute
  AuthedCompanySlugPanelInvitesIndexRoute: typeof AuthedCompanySlugPanelInvitesIndexRoute
}

const AuthedCompanySlugPanelInvitesRouteRouteChildren: AuthedCompanySlugPanelInvitesRouteRouteChildren =
  {
    AuthedCompanySlugPanelInvitesInviteIdRoute:
      AuthedCompanySlugPanelInvitesInviteIdRoute,
    AuthedCompanySlugPanelInvitesNewRoute:
      AuthedCompanySlugPanelInvitesNewRoute,
    AuthedCompanySlugPanelInvitesIndexRoute:
      AuthedCompanySlugPanelInvitesIndexRoute,
  }

const AuthedCompanySlugPanelInvitesRouteRouteWithChildren =
  AuthedCompanySlugPanelInvitesRouteRoute._addFileChildren(
    AuthedCompanySlugPanelInvitesRouteRouteChildren,
  )

interface AuthedCompanySlugPanelOrdersRouteRouteChildren {
  AuthedCompanySlugPanelOrdersOrderIdRoute: typeof AuthedCompanySlugPanelOrdersOrderIdRoute
  AuthedCompanySlugPanelOrdersNewRoute: typeof AuthedCompanySlugPanelOrdersNewRoute
  AuthedCompanySlugPanelOrdersIndexRoute: typeof AuthedCompanySlugPanelOrdersIndexRoute
}

const AuthedCompanySlugPanelOrdersRouteRouteChildren: AuthedCompanySlugPanelOrdersRouteRouteChildren =
  {
    AuthedCompanySlugPanelOrdersOrderIdRoute:
      AuthedCompanySlugPanelOrdersOrderIdRoute,
    AuthedCompanySlugPanelOrdersNewRoute: AuthedCompanySlugPanelOrdersNewRoute,
    AuthedCompanySlugPanelOrdersIndexRoute:
      AuthedCompanySlugPanelOrdersIndexRoute,
  }

const AuthedCompanySlugPanelOrdersRouteRouteWithChildren =
  AuthedCompanySlugPanelOrdersRouteRoute._addFileChildren(
    AuthedCompanySlugPanelOrdersRouteRouteChildren,
  )

interface AuthedCompanySlugPanelPricingPriceListIdRouteRouteChildren {
  AuthedCompanySlugPanelPricingPriceListIdEditRoute: typeof AuthedCompanySlugPanelPricingPriceListIdEditRoute
  AuthedCompanySlugPanelPricingPriceListIdIndexRoute: typeof AuthedCompanySlugPanelPricingPriceListIdIndexRoute
}

const AuthedCompanySlugPanelPricingPriceListIdRouteRouteChildren: AuthedCompanySlugPanelPricingPriceListIdRouteRouteChildren =
  {
    AuthedCompanySlugPanelPricingPriceListIdEditRoute:
      AuthedCompanySlugPanelPricingPriceListIdEditRoute,
    AuthedCompanySlugPanelPricingPriceListIdIndexRoute:
      AuthedCompanySlugPanelPricingPriceListIdIndexRoute,
  }

const AuthedCompanySlugPanelPricingPriceListIdRouteRouteWithChildren =
  AuthedCompanySlugPanelPricingPriceListIdRouteRoute._addFileChildren(
    AuthedCompanySlugPanelPricingPriceListIdRouteRouteChildren,
  )

interface AuthedCompanySlugPanelPricingRouteRouteChildren {
  AuthedCompanySlugPanelPricingPriceListIdRouteRoute: typeof AuthedCompanySlugPanelPricingPriceListIdRouteRouteWithChildren
  AuthedCompanySlugPanelPricingNewRoute: typeof AuthedCompanySlugPanelPricingNewRoute
  AuthedCompanySlugPanelPricingIndexRoute: typeof AuthedCompanySlugPanelPricingIndexRoute
}

const AuthedCompanySlugPanelPricingRouteRouteChildren: AuthedCompanySlugPanelPricingRouteRouteChildren =
  {
    AuthedCompanySlugPanelPricingPriceListIdRouteRoute:
      AuthedCompanySlugPanelPricingPriceListIdRouteRouteWithChildren,
    AuthedCompanySlugPanelPricingNewRoute:
      AuthedCompanySlugPanelPricingNewRoute,
    AuthedCompanySlugPanelPricingIndexRoute:
      AuthedCompanySlugPanelPricingIndexRoute,
  }

const AuthedCompanySlugPanelPricingRouteRouteWithChildren =
  AuthedCompanySlugPanelPricingRouteRoute._addFileChildren(
    AuthedCompanySlugPanelPricingRouteRouteChildren,
  )

interface AuthedCompanySlugPanelProductsProductIdRouteRouteChildren {
  AuthedCompanySlugPanelProductsProductIdEditRoute: typeof AuthedCompanySlugPanelProductsProductIdEditRoute
  AuthedCompanySlugPanelProductsProductIdIndexRoute: typeof AuthedCompanySlugPanelProductsProductIdIndexRoute
}

const AuthedCompanySlugPanelProductsProductIdRouteRouteChildren: AuthedCompanySlugPanelProductsProductIdRouteRouteChildren =
  {
    AuthedCompanySlugPanelProductsProductIdEditRoute:
      AuthedCompanySlugPanelProductsProductIdEditRoute,
    AuthedCompanySlugPanelProductsProductIdIndexRoute:
      AuthedCompanySlugPanelProductsProductIdIndexRoute,
  }

const AuthedCompanySlugPanelProductsProductIdRouteRouteWithChildren =
  AuthedCompanySlugPanelProductsProductIdRouteRoute._addFileChildren(
    AuthedCompanySlugPanelProductsProductIdRouteRouteChildren,
  )

interface AuthedCompanySlugPanelProductsRouteRouteChildren {
  AuthedCompanySlugPanelProductsProductIdRouteRoute: typeof AuthedCompanySlugPanelProductsProductIdRouteRouteWithChildren
  AuthedCompanySlugPanelProductsNewRoute: typeof AuthedCompanySlugPanelProductsNewRoute
  AuthedCompanySlugPanelProductsIndexRoute: typeof AuthedCompanySlugPanelProductsIndexRoute
}

const AuthedCompanySlugPanelProductsRouteRouteChildren: AuthedCompanySlugPanelProductsRouteRouteChildren =
  {
    AuthedCompanySlugPanelProductsProductIdRouteRoute:
      AuthedCompanySlugPanelProductsProductIdRouteRouteWithChildren,
    AuthedCompanySlugPanelProductsNewRoute:
      AuthedCompanySlugPanelProductsNewRoute,
    AuthedCompanySlugPanelProductsIndexRoute:
      AuthedCompanySlugPanelProductsIndexRoute,
  }

const AuthedCompanySlugPanelProductsRouteRouteWithChildren =
  AuthedCompanySlugPanelProductsRouteRoute._addFileChildren(
    AuthedCompanySlugPanelProductsRouteRouteChildren,
  )

interface AuthedCompanySlugPanelRouteRouteChildren {
  AuthedCompanySlugPanelCompanyRouteRoute: typeof AuthedCompanySlugPanelCompanyRouteRouteWithChildren
  AuthedCompanySlugPanelCustomersRouteRoute: typeof AuthedCompanySlugPanelCustomersRouteRouteWithChildren
  AuthedCompanySlugPanelDocumentsRouteRoute: typeof AuthedCompanySlugPanelDocumentsRouteRouteWithChildren
  AuthedCompanySlugPanelInvitesRouteRoute: typeof AuthedCompanySlugPanelInvitesRouteRouteWithChildren
  AuthedCompanySlugPanelOrdersRouteRoute: typeof AuthedCompanySlugPanelOrdersRouteRouteWithChildren
  AuthedCompanySlugPanelPricingRouteRoute: typeof AuthedCompanySlugPanelPricingRouteRouteWithChildren
  AuthedCompanySlugPanelProductsRouteRoute: typeof AuthedCompanySlugPanelProductsRouteRouteWithChildren
  AuthedCompanySlugPanelIndexRoute: typeof AuthedCompanySlugPanelIndexRoute
}

const AuthedCompanySlugPanelRouteRouteChildren: AuthedCompanySlugPanelRouteRouteChildren =
  {
    AuthedCompanySlugPanelCompanyRouteRoute:
      AuthedCompanySlugPanelCompanyRouteRouteWithChildren,
    AuthedCompanySlugPanelCustomersRouteRoute:
      AuthedCompanySlugPanelCustomersRouteRouteWithChildren,
    AuthedCompanySlugPanelDocumentsRouteRoute:
      AuthedCompanySlugPanelDocumentsRouteRouteWithChildren,
    AuthedCompanySlugPanelInvitesRouteRoute:
      AuthedCompanySlugPanelInvitesRouteRouteWithChildren,
    AuthedCompanySlugPanelOrdersRouteRoute:
      AuthedCompanySlugPanelOrdersRouteRouteWithChildren,
    AuthedCompanySlugPanelPricingRouteRoute:
      AuthedCompanySlugPanelPricingRouteRouteWithChildren,
    AuthedCompanySlugPanelProductsRouteRoute:
      AuthedCompanySlugPanelProductsRouteRouteWithChildren,
    AuthedCompanySlugPanelIndexRoute: AuthedCompanySlugPanelIndexRoute,
  }

const AuthedCompanySlugPanelRouteRouteWithChildren =
  AuthedCompanySlugPanelRouteRoute._addFileChildren(
    AuthedCompanySlugPanelRouteRouteChildren,
  )

interface AuthedCompanySlugRouteRouteChildren {
  AuthedCompanySlugFullRouteRoute: typeof AuthedCompanySlugFullRouteRouteWithChildren
  AuthedCompanySlugPanelRouteRoute: typeof AuthedCompanySlugPanelRouteRouteWithChildren
}

const AuthedCompanySlugRouteRouteChildren: AuthedCompanySlugRouteRouteChildren =
  {
    AuthedCompanySlugFullRouteRoute:
      AuthedCompanySlugFullRouteRouteWithChildren,
    AuthedCompanySlugPanelRouteRoute:
      AuthedCompanySlugPanelRouteRouteWithChildren,
  }

const AuthedCompanySlugRouteRouteWithChildren =
  AuthedCompanySlugRouteRoute._addFileChildren(
    AuthedCompanySlugRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedCompanySlugRouteRoute: typeof AuthedCompanySlugRouteRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCompanySlugRouteRoute: AuthedCompanySlugRouteRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
