/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedCompanySlugRouteImport } from './routes/_authed/$companySlug'
import { Route as AuthedCompanySlugIndexRouteImport } from './routes/_authed/$companySlug/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompanySlugRoute = AuthedCompanySlugRouteImport.update({
  id: '/$companySlug',
  path: '/$companySlug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompanySlugIndexRoute = AuthedCompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedCompanySlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/verify': typeof AuthVerifyRoute
  '/$companySlug': typeof AuthedCompanySlugRouteWithChildren
  '/$companySlug/': typeof AuthedCompanySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/verify': typeof AuthVerifyRoute
  '/$companySlug': typeof AuthedCompanySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_authed/$companySlug': typeof AuthedCompanySlugRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/$companySlug/': typeof AuthedCompanySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/verify' | '/$companySlug' | '/$companySlug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/verify' | '/$companySlug'
  id:
    | '__root__'
    | '/_auth'
    | '/_authed'
    | '/_auth/sign-in'
    | '/_auth/verify'
    | '/_authed/$companySlug'
    | '/_authed/'
    | '/_authed/$companySlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$companySlug': {
      id: '/_authed/$companySlug'
      path: '/$companySlug'
      fullPath: '/$companySlug'
      preLoaderRoute: typeof AuthedCompanySlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$companySlug/': {
      id: '/_authed/$companySlug/'
      path: '/'
      fullPath: '/$companySlug/'
      preLoaderRoute: typeof AuthedCompanySlugIndexRouteImport
      parentRoute: typeof AuthedCompanySlugRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthedCompanySlugRouteChildren {
  AuthedCompanySlugIndexRoute: typeof AuthedCompanySlugIndexRoute
}

const AuthedCompanySlugRouteChildren: AuthedCompanySlugRouteChildren = {
  AuthedCompanySlugIndexRoute: AuthedCompanySlugIndexRoute,
}

const AuthedCompanySlugRouteWithChildren =
  AuthedCompanySlugRoute._addFileChildren(AuthedCompanySlugRouteChildren)

interface AuthedRouteChildren {
  AuthedCompanySlugRoute: typeof AuthedCompanySlugRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCompanySlugRoute: AuthedCompanySlugRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
