import {
  COUNTERPARTY_BANK_MFO_MAX,
  COUNTERPARTY_BANK_NAME_MAX,
  COUNTERPARTY_EDRPOU_MAX,
  COUNTERPARTY_EMAIL_MAX,
  COUNTERPARTY_IBAN_MAX,
  COUNTERPARTY_LEGAL_ADDRESS_MAX,
  COUNTERPARTY_NAME_MAX,
  COUNTERPARTY_NOTES_MAX,
  COUNTERPARTY_PHONE_MAX,
  CUSTOMER_EMAIL_MAX,
  CUSTOMER_NAME_MAX,
  CUSTOMER_NOTES_MAX,
  CUSTOMER_PHONE_MAX,
  GROUP_DESCRIPTION_MAX,
  GROUP_NAME_MAX,
  LIST_COUNTERPARTIES_SEARCH_MAX,
  LIST_CUSTOMERS_SEARCH_MAX,
  LIST_GROUPS_SEARCH_MAX,
} from "@showzy/validation/customers";

export {
  COUNTERPARTY_BANK_MFO_MAX,
  COUNTERPARTY_BANK_NAME_MAX,
  COUNTERPARTY_EDRPOU_MAX,
  COUNTERPARTY_EMAIL_MAX,
  COUNTERPARTY_IBAN_MAX,
  COUNTERPARTY_LEGAL_ADDRESS_MAX,
  COUNTERPARTY_NAME_MAX,
  COUNTERPARTY_NOTES_MAX,
  COUNTERPARTY_PHONE_MAX,
  CUSTOMER_EMAIL_MAX,
  CUSTOMER_NAME_MAX,
  CUSTOMER_NOTES_MAX,
  CUSTOMER_PHONE_MAX,
  GROUP_DESCRIPTION_MAX,
  GROUP_NAME_MAX,
  LIST_COUNTERPARTIES_SEARCH_MAX,
  LIST_CUSTOMERS_SEARCH_MAX,
  LIST_GROUPS_SEARCH_MAX,
};

/**
 * Page size for drained lookups (group chips, price-list names). Matches
 * the contract max on `customers.listGroups` / `pricing.listPriceLists`.
 */
export const CUSTOMERS_LOOKUP_PAGE_SIZE = 50;

/** Canvas notes textarea `rows={5}` — Class B via TextField multiline. */
export const CUSTOMER_FORM_NOTES_LINES = 5;

/** Canvas GroupEditor description `rows={4}` — Class B via TextField. */
export const GROUP_FORM_DESCRIPTION_LINES = 4;

/** Canvas CounterpartyEditor legal address `rows={3}` — Class B. */
export const COUNTERPARTY_FORM_ADDRESS_LINES = 3;

/** Canvas CounterpartyEditor notes `rows={4}` — Class B via TextField. */
export const COUNTERPARTY_FORM_NOTES_LINES = 4;
