import {
  darkGlassFallback,
  darkGlassFallbackDense,
  darkGlassFallbackPressed,
  darkPalette,
  hitTarget,
  iconSize,
  otpCellMaxWidth,
  pressedOpacity,
  radii,
  shadows,
  spacing,
  squircle,
  typography,
} from "./tokens";

export const darkTheme = {
  colors: darkPalette,
  spacing,
  radii,
  typography,
  shadows,
  hitTarget,
  iconSize,
  squircle,
  pressedOpacity,
  otpCellMaxWidth,
  glassFallback: darkGlassFallback,
  glassFallbackDense: darkGlassFallbackDense,
  glassFallbackPressed: darkGlassFallbackPressed,
} as const;
