import {
  hitTarget,
  iconSize,
  lightGlassFallback,
  lightGlassFallbackDense,
  lightGlassFallbackPressed,
  lightPalette,
  otpCellMaxWidth,
  pressedOpacity,
  radii,
  shadows,
  spacing,
  squircle,
  typography,
} from "./tokens";

export const lightTheme = {
  colors: lightPalette,
  spacing,
  radii,
  typography,
  shadows,
  hitTarget,
  iconSize,
  squircle,
  pressedOpacity,
  otpCellMaxWidth,
  glassFallback: lightGlassFallback,
  glassFallbackDense: lightGlassFallbackDense,
  glassFallbackPressed: lightGlassFallbackPressed,
} as const;
